---
kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: rancher/hardened-build-base:v1.20.7b3
  commands:
  - make DRONE_TAG=${DRONE_TAG}
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    ref:
      include:
      - refs/heads/main
      - refs/pull/**
      - refs/tags/*

- name: publish
  image: rancher/hardened-build-base:v1.20.7b3
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag

- name: scan
  image: rancher/hardened-build-base:v1.20.7b3
  commands:
  - make DRONE_TAG=${DRONE_TAG} image-scan
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    ref:
      include:
      - refs/heads/main
      - refs/pull/**
      - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  pull: always
  image: rancher/hardened-build-base:v1.20.7b3
  commands:
  - make DRONE_TAG=${DRONE_TAG}
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    ref:
      include:
      - refs/heads/main
      - refs/pull/**
      - refs/tags/*

- name: publish
  image: rancher/hardened-build-base:v1.20.7b3
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag

- name: scan
  image: rancher/hardened-build-base:v1.20.7b3
  commands:
  - make DRONE_TAG=${DRONE_TAG} image-scan
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    ref:
      include:
      - refs/heads/main
      - refs/pull/**
      - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: manifest
platform:
  os: linux
  arch: amd64
steps:
- name: push
  image: plugins/manifest:1.2.3
  settings:
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    spec: manifest.tmpl
  when:
    event:
    - tag

depends_on:
- linux-amd64
- linux-arm64
...
