name: Republish Latest
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
  workflow_dispatch:

permissions:
    contents: write
    id-token: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Read Secrets"
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/github/rancher-release-team-auto-tagger/app-credentials appId | APP_ID ;
            secret/data/github/repo/${{ github.repository }}/github/rancher-release-team-auto-tagger/app-credentials privateKey | PRIVATE_KEY

      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.PRIVATE_KEY }}

      - name: Republish Latest Release
        uses: rancher/ecm-distro-tools/actions/republish-latest@master
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          commitish: 'main'
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
